### ISSUE TITLE
No 'Done' button on Android feedback modal

### ISSUE THREAD

**Issue by sirMuffles91** [bitstadium/HockeySDK-Cordova#102]
There does not seem to be a 'done' button in the Android feedback modal like there is in the iOS version of the app. Is there any way to enable that? Otherwise the user has to exit the app and come back in before they can access the app again.

**Comment by bmourat** [comment]
Hi @sirMuffles91 

How are you displaying feedback window modally on android?

**Comment by sirMuffles91** [comment]
I am just using hockeyapp.composeFeedback(null, null, false, errorLog);

**Comment by bmourat** [comment]
For android platform feedback window is shown as a normal activity, so you can exit this activity with "back" button. Doesn't it work? What happens when you press it?

**Comment by sirMuffles91** [comment]
When pressing the hardware back button it closes the entire app at the moment

**Comment by bmourat** [comment]
Ok. I'm trying to understand when in the lifecycle of the app scope.showFeedback is called. Is it a button click handler or something else?

**Comment by sirMuffles91** [comment]
Yes sorry it is just a function bound to ng-click in a controller. So I have a feedback page with a button that when clicked calls the hockeyapp.composeFeedback method

**Comment by bmourat** [comment]
And to be clear there are no custom backbutton listeners registered?

**Comment by sirMuffles91** [comment]
No there are no custom backbutton listeners in the project

**Comment by bmourat** [comment]
Thanks, let me investigate this :)

**Comment by sirMuffles91** [comment]
Thanks so much for the help :)

**Comment by bmourat** [comment]
I suppose you are using ionic framework and [ionic-hockeyapp wrapper](https://www.npmjs.com/package/ionic-hockeyapp). If so, see [this comments and block of code](https://github.com/hicsail/ionic-hockeyapp/blob/master/example/src/app/app.component.ts#L21), i think that is your case.

**Comment by sirMuffles91** [comment]
Unfortunately I am stuck on ionic 1 at the moment but will just adapt that code. Thanks so much for all the help!

**Comment by bmourat** [comment]
If you have any more questions, i'll be glad to help:)

**Comment by alexhisen** [comment]
If you have a custom back button handler, you can prompt the user before exiting the app, but the Back button exit from the feedback dialog is sporadic in cordova (without ionic). Sometimes it'll just exit to the app and the app will not see the back button event and other times it will.

In any event, a Done button or the like (or just closing it automatically) will be much more user-friendly.
