### ISSUE TITLE
Screenshot full page length and expose separate API

### ISSUE THREAD

**Issue by alexhisen** [bitstadium/HockeySDK-Cordova#104]
1. Screenshots would be a lot more useful if the entire page length (including area above and below visible viewport) could be captured.
2. Often the page with the problem is one step away from the 'Help' screen in which the user can start the Feedback process, so a separate API method that could be used to generate a screenshot when the user navigates to the 'Help' screen and then later attached to the feedback would make it a lot more valuable.

**Comment by elamalani** [comment]
@alexhisen Thanks for sharing your feedback on the HockeySDK "Feedback" feature. This looks like new feature request in the SDK. Our team is actively working on [App Center](appcenter.ms) which is the next generation of [HockeyApp](https://hockeyapp.net/appcenter/about/). Our plan is to add all new features in App Center going forward. We won't support this feature in HockeySDK but your feedback will help us design this better in App Center SDK.

Thanks!
