### ISSUE TITLE
Is this the plugin to use with AppCenter?

### ISSUE THREAD

**Issue by syonip** [bitstadium/HockeySDK-Cordova#111]
Following the link in this guide to create an account at http://hockeyapp.net/, I get redirected to https://appcenter.ms - where it seems to be hosted now.
After creating an app there, the tutorial says to install `cordova-plugin-appcenter-analytics` and `cordova-plugin-appcenter-crashes`.
What's the relation between these plugins? Which should I use?
Thanks.

**Comment by lumaxis** [comment]
Information about the App Center SDK for Cordova can be found here: https://github.com/Microsoft/AppCenter-SDK-Cordova

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by syonip** [comment]
Seeing as "On November 16, 2019, HockeyApp will transition fully to App Center." (https://hockeyapp.net/), maybe it should be written in the readme of this repo, so that people won't use this plugin for new projects?

**Comment by Jamminroot** [comment]
Hey @syonip, thanks for getting in touch.
I've addressed your request to PM. Ill keep you updated through this thread.
