### ISSUE TITLE
UpdatePrompt automatically activated on iOS but not on Android?

### ISSUE THREAD

**Issue by piotrowski** [bitstadium/HockeySDK-Cordova#16]
I'm trying to find out why the UpdatePrompt is no triggered on our Android app. As we only implemented the bare minimum, I am even more confused why it **is** triggered on iOS.

Is it possible that the prompt is always automatically triggered on iOS, but additional code is neede for Android?

**Comment by piotrowski** [comment]
Okay, first hint found here:

> 3.8 In-App-Updates (Beta & Enterprise only)
> [...]
> This module automatically disables itself when running in an App Store build by default!

http://support.hockeyapp.net/kb/client-integration-ios-mac-os-x/hockeyapp-for-ios#betaupdates

**Comment by piotrowski** [comment]
Just to make sure I just asked the HockeyApp guys again:
http://support.hockeyapp.net/discussions/problems/49574-integrate-updateprompt-ios-automatically-android-manually

**Comment by piotrowski** [comment]
Yep, seem to be that way (via answer from Thomas):

> On iOS, you have to initialize the class `BITHockeyManager` (minimum 3 lines of code). On Android, you have to initialize the classes `UpdateManager` and `CrashManager` (minimum 2 lines of code).

This means we could a) explicity disable this for the default .start() on iOS and add another function to start it so both plattforms don't start this automatically,  b) add the UpdateManager call on Android so both platforms start this automatically when calling .start() or c) update the difference in behaviour in the README so users are aware of it.

I don't really have a preference yet...

**Comment by peutetre** [comment]
Having the same behaviour across platforms is the best IMHO, I vote for 'a' ;-)

**Comment by piotrowski** [comment]
Okay, then I'll create a PR later that includes the necessary `[[BITHockeyManager sharedHockeyManager] setDisableUpdateManager: YES]; //disable crash reporting` and makes sure there is a matching method for iOS to start the UpdatePrompt stuff - plus the documentation for that.

**Comment by peutetre** [comment]
cool thanks @piotrowski!

**Comment by piotrowski** [comment]
Ok, finally revisited this because I had to add the `checkForUpdate` to my Android version of the app so that HockeyApp finally triggers the Update windows on starting the App.

I'm not sure anymore that it's a good idea to go away from the way HockeyApp does it by default - or at least we would have to put some thought how to mention it in the README for users checking out this plugin... otherwise this will create additional confusion.

**Comment by piotrowski** [comment]
Just noticed that the Update prompt on iOS is also triggered when the app comes back into foreground, not only on start. Maybe the docs then should include information on how to achieve this on Android, too - to make them both identical. Also depending on what we decide, we need docs on how to re-enable this on iOS.

**Comment by jskrepnek** [comment]
@piotrowski I've spent the day you mentioned (not quite) tracking updates not prompting for Android.  Yet I'm still not clear why we wouldn't want that to happen automatically for both platforms - or maybe I'm reading your thinking wrong.

Checking for updates OOTB on startup and resume for both platforms feels like the right default behaviour.

I'm going to manually add a check for update for android too; it will be a breaking change if this ever happens automatically, resulting in two prompts.  :).

Thanks.

**Comment by piotrowski** [comment]
@jskrepnek Yay, it's not just me any more.

But seriously, I now think it should be made an explicit parameter of `start` if it should automatically look for updates - for iOS and Android. The documentation can automatically have this set to `true` as this is what probably most users expect. Still, it should be possible not to check for updates (as it is with the plain HockeyApp on Android afaik) but only start it. 

The resume-stuff probably isn't that easy, as we would have to listen for Cordova events or something... Or do it in the native Android code bits.

**Comment by Alex-Sessler** [comment]
I've recently started using the plugin too and have found problems in iOS with the automatic check for updates. It checks for updates even if I didn't call the function, tells me there is an update when i just installed the latest update and when I click on "install" it just ends up showing "Cannot connect to sdk.hockeyapp.net".

**Comment by julrich** [comment]
@Alex-Sessler: Did you ever resolve this? Running into the exact same problem right now

**Comment by julrich** [comment]
Just for a resolution, I was using the wrong App ID inside my JS (the same as the one for Android, for which it was correct). Works fine now!

**Comment by gibo** [comment]
@piotrowski did your suggestion get implemented? if not, I can do it.
