### ISSUE TITLE
iOS: xCode warning

### ISSUE THREAD

**Issue by KODerFunk** [bitstadium/HockeySDK-Cordova#27]
`
appdir/platforms/ios/MyApp/Plugins/cordova-plugin-hockeyapp/HockeyApp.m:34:73: Sending 'HockeyApp *const __strong' to parameter of incompatible type 'id<BITHockeyManagerDelegate>'
`

**Comment by lostintangent** [comment]
@KODerFunk Did this impact the plugin behavior at all for you? I can repro the warning, but everything seems to work completely fine. I'll send out a PR to address the warning, but I just wanted to double check that you weren't blocked by this. Thanks for reporting it!

**Comment by lostintangent** [comment]
Resolved via #34. We'll release this fix in the next NPM release, which will likely be tomorrow-ish. In the meantime, if this is blocking you, you could install the plugin from this repo. Thanks for reporting it!
