### ISSUE TITLE
Android: dosnt work

### ISSUE THREAD

**Issue by KODerFunk** [bitstadium/HockeySDK-Cordova#28]
Integrate in my app (Cordova 5.4.1), build release, sign, realign, upload to hockeyapp, download via mobile-hockey-app to 2 android devices, and no have stats in hocheyapp-web-rink:
`No statistics found. Please integrate HockeySDK to collect analytics, crash reports, and feedback:`

Run my app on devise via Android-Studio and see in logs:
```
03-03 09:58:47.034 28547-28611/? D/HockeyApp: Looking for exceptions in: /data/data/com.evrone.myapp/files
03-03 09:58:47.034 28547-28611/? I/System.out: mkdir failed: EEXIST (File exists) path = /data/data/com.evrone.myapp/files
03-03 09:58:47.034 28547-28611/? D/HockeyApp: Current handler class = net.hockeyapp.android.ExceptionHandler
```

**Comment by lostintangent** [comment]
@KODerFunk Did you add the call to hockeyapp.start in your app and make sure it was passing the correct app ID? I haven't been able to repro this issue. When I install the plugin, call start, and then run it, I can see feedback, forced crashes, etc. in the HockeyApp portal. 

Did this issue ever resolve for you, or are you still hitting it?

**Comment by KODerFunk** [comment]
Statistics come, but later. There is some delay? Only for Android?

**Comment by lostintangent** [comment]
@KODerFunk Do you think this is an issue with the Cordova plugin, or maybe something to ask the HockeyApp team about the latency for certain statistics?

**Comment by lostintangent** [comment]
I'm going to close this issue for now since I can't repro any issues with the client plugin not reporting data correctly. If you're seeing long delays, could you report the issue to the HockeyApp service team? Otherwise, please re-open this if you think there is something we need to investigate in the Cordova client. Thanks!
