### ISSUE TITLE
Feedback (with image) in landscape only mode

### ISSUE THREAD

**Issue by leecrossley** [bitstadium/HockeySDK-Cordova#42]
I have an iPad app which is restricted to running in landscape mode. This breaks the layout of the feedback dialog when adding an image.

![img_0003](https://cloud.githubusercontent.com/assets/807783/14430337/15f59a38-fff9-11e5-99e1-2c5bede181c3.PNG)

**Comment by lostintangent** [comment]
That is clearly broken :/ Let me investigate this issue and get back to you on a resolution. Sorry for the issue!

**Comment by lumaxis** [comment]
@leecrossley I just tried reproducing this in a sample app but unfortunately, there everything looked normal.
Can you provide any further details how to get a reliable reproduction?

**Comment by lostintangent** [comment]
@leecrossley Could you let us know which version of Cordova iOS (by running `cordova platform ls`) your app is using, and what version of iOS you're running the simulator using? I also haven't been able to repro this issue, so it would be awesome to know your exact setup so I could try to figure out what the issue might be. Thanks!

**Comment by leecrossley** [comment]
Hi guys - sorry for the delay. I _think_ it's to do with the `cordova-plugin-screen-orientation` plugin calling `screen.lockOrientation("landscape")` - I've now changed the code so that it only locks the orientation on Android. If it's not that, I'll reopen :)

**Comment by lostintangent** [comment]
@leecrossley Awesome! Thanks for letting us know :)
