### ISSUE TITLE
checkForUpdate doesn't work on iOS

### ISSUE THREAD

**Issue by mj22552** [bitstadium/HockeySDK-Cordova#43]
Tried using the this function and nothing happens. I do get a success callback when invoking it but nothing seems to happen. Using it on actual device. iOS 9.3. Othe functions like feedback and crash work fine.

**Comment by lostintangent** [comment]
@mj22552 In your testing, is there actually an update available on the server when you call `checkForUpdate`? It will only display the update prompt to the user if an update is available (in order to be an non-invasive as possible), so it would be expected to simply executed the success callback if there isn't an update available.

**Comment by lostintangent** [comment]
@mj22552 I'm going to close this bug for now since I can't get it to repro. Please feel free to re-open it if the problem persists after you double-check that your app had an update. Thanks!

**Comment by dorgold** [comment]
Hey, i am experiencing the same issue. It works great when i sign the app with my developer identity, but when i use the enterprise signing identity i never get an update notice (even if there is an available newer version.

**Comment by johnborges** [comment]
I'm unable to get this working for both cases 👎. Developer Identity or Enterprise Signing. 

@lostintangent Can you post a configuration example of how an app should be setup to enable this?

**Comment by tharrington** [comment]
@lostintangent same here!

**Comment by tharrington** [comment]
@johnborges did you solve this issue?

**Comment by johnborges** [comment]
Nope. I have never gotten this feature to work on iOS.

**Comment by tharrington** [comment]
@johnborges i did $ionic platform remove ios and then re-added it... now it's working.
