### ISSUE TITLE
Create a typescript definition

### ISSUE THREAD

**Issue by dorgold** [bitstadium/HockeySDK-Cordova#47]
When using this plugin in a typescript environment (Ionic 2 for example). A typescript definition file is really helpful. This can be distributed as part of the npm package or separately via https://github.com/DefinitelyTyped/DefinitelyTyped .

**Comment by lostintangent** [comment]
We've been meaning to do this, and will try to throw it together next week. Sorry for the delayed response!

**Comment by BurningDog** [comment]
Bump ;)

**Comment by oz-frog** [comment]
Bump indeed :) I ,made my own hockeyapp.d.ts it be good if the tsd file was added to the npm/typings package so it in line with modern dev tools.

**Comment by BurningDog** [comment]
@oz-frog that sounds great - any chance you'd want to upload that hockeyapp.d.ts file here?

**Comment by oz-frog** [comment]
## Adding type definition to Cordova-plugin-hockeyapp to use in ionic 2 typescript project.

Hello,

I have been busy with other things, (got to earn a little money from time to time :))

Roger asked me to upload the typescript definition for the cordova-plugin-hockeyapp.
First  I would like to try to demystify the situation for those who are hitting these bumps while playing with ionic 2 typescript projects and not ionic-native plugins such as this one.  I want to do this as the build process and project structure can be so complex at times that once things ain't working, it can be difficult to understand. Shall not fear , these are only bits and if they don't work for us we can always wipe them up, and start over, we are still in control. :)

Regard to making this plugin compatible with Ionic 2 , the ideal place would be to have it included as part of the ionic-native plugin distribution. The Ionic 2 team is awesome and ionic-native modules are beautifully integrated with the angular 2 typescript environment, but this is not the case yet for the HockeyApp Cordova plugin. Maybe we should look into porting this plugin to ionic-native. It would be worthwhile for those interested. anyone?

The other option would be to modify the npm package to include typings, until then to have basic type info available for the plugin so it works well in an ionic 2 typescript project this what can be done.

This description is applicable for Ionic 2 typescript projects: 

Add a typescript definition for the module inside the app folder, so the editor and compiler can find it easily. For this purpose, I created a file in my project named ./apps/hockeyapp.d.ts, this file could be named anything else or even added to an existing file. the content of this file is:

> **export interface hockeyapp** {
>  start: (success: any, failure: any, appId: any, autoSend?: any, ignoreDefaultHandler?: any, loginMode?:any, appSecret?: any) => void;
>  feedback: (success: any, failure: any) => void;
>  forceCrash: (success: any, failure: any) => void;
>  checkForUpdate: (success: any, failure: any) => void;
>  addMetaData: (success: any, failure: any, data: any) => void;
>  trackEvent: (success: any, failure: any, eventName: any) => void;

>  loginMode: {
>   ANONYMOUS: any,
>    EMAIL_ONLY: any,
>    EMAIL_PASSWORD: any,
>    VALIDATE: any
>  }
>}
>**declare var hockeyapp:hockeyapp;**

 and that's all after that you can start referring to hockeyapp variable in your app and see method signatures.

I used typescript type '**any**' a lot cause I do not really care about compiler type safety checks at this stage, just wanted the signatures to show up; also note the '**?**' for optional parameters.

I installed the plugin with the following cordova CLI commands: 
> cordova plugin add cordova-plugin-hockeyapp@latest which picks latest from npm repository

Cheers

**Comment by jayhuang75** [comment]
@oz-frog, I'm more wondering how to use in the ionic2 app. Am I need to add the Js path in the index.html because I get hockeyapp no found issuses.

**Comment by pvdyck** [comment]
FYI https://github.com/jsiegmund/submerged/blob/master/src/Mobile/MobileApp/scripts/typings/browser/ambient/hockeyapp/hockeyapp.d.ts

**Comment by Eetezadi** [comment]
Any one has the merci to explain for a beginner how to implement this typescript definition in an ionic 2 project? Very appreciated.

**Comment by gregfrasco** [comment]
I created an ionic provider to add hockey app into my ionic project. I added it to this repo here
[ionic-hockeyapp](https://github.com/hicsail/ionic-hockeyapp)

**Comment by Jacob-McKay** [comment]
@gregfrasco module looks promising, though you might want to ensure the 'start' call succeeds before you start invoking the SDK to send events and check for updates.  For my ionic2 project here's what my declarations.d.ts file looks like (in my typescript src/ directory), which is how I've gotten intellisense for hockeyapp.

`
/*
  Declaration files are how the Typescript compiler knows about the type information(or shape) of an object.
  They're what make intellisense work and make Typescript know all about your code.

  A wildcard module is declared below to allow third party libraries to be used in an app even if they don't
  provide their own type declarations.

  To learn more about using third party libraries in an Ionic app, check out the docs here:
  http://ionicframework.com/docs/v2/resources/third-party-libs/

  For more info on type definition files, check out the Typescript docs here:
  https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html
*/
declare module '*';

interface IHockeyAppSDK {
	start(successCallback: Function, errorCallback: Function, appId: string, autoSend?: boolean, ignoreDefaultHandler?: boolean, loginMode?: string, appSecret?: string): void;
	forceCrash(): void;
	feedback(): void;
	composeFeedback(successCallback: Function, errorCallback: Function, includeScreenshot: boolean, additionalData: Object);
	checkForUpdate(): void;
	addMetaData(successCallback: Function, errorCallback: Function, metadata: Object): void;
	trackEvent(successCallback: Function, errorCallback: Function, eventName: string): void;
}

`

**Comment by cocowalla** [comment]
@gregfrasco would be nice if you could adapt it for [Ionic Native](https://github.com/ionic-team/ionic-native) and send them a PR?
