### ISSUE TITLE
Auto send crash reports is not working

### ISSUE THREAD

**Issue by dorgold** [bitstadium/HockeySDK-Cordova#48]
Calling hockeyapp.start method with true in the autoSend parameter doesn't cause the plugin to auto send crash reports on iOS.

This seems to be due to the way the autoSend value is checked in the objective c code. The value is checked using `[autoSend isEqual:@"true"]`.
Debugging the code showed that the value passed to objective c is "1" for true and "0" for false.

**Comment by hilkeheremans** [comment]
@lostintangent It seems this fix hasn't been released yet. Would anyone mind bumping the version and releasing it as a cordova plugin?

Easy to work around using direct fetch from git but that isn't exactly good practice, is it. ;-)
