### ISSUE TITLE
support for Windows

### ISSUE THREAD

**Issue by lucorn** [bitstadium/HockeySDK-Cordova#52]
Are there any plans to support Windows alongside iOS and Android? Timeframe?

**Comment by lostintangent** [comment]
We definitely plan to add this. We don't unfortunately have any concrete plans yet, but we'll keep you posted and will use this bug to track the feature work. Thanks!

**Comment by almost92** [comment]
any update on this ?

**Comment by cadesalaberry** [comment]
Wondering the same.

**Comment by TroubleMakerBen** [comment]
Hey everyone,

Sorry that things have been very silent over here.
We're not planning on adding support for UWP apps to HockeySDK-Cordova. We are focussing on [MobileCenter](https://www.hockeyapp.net/blog/2016/11/16/mobile-center-next-generation-hockeyapp.html) and Cordova SDKs are on the roadmap but we cannot give an ETA for this. We hope you understand.

We appreciate any feedback. Thanks for using HockeyApp!

**Comment by cadesalaberry** [comment]
No worries, thanks for the feedback !

Do you know of any other product that could help us gather analytics or logs from a cordova app in production ?

**Comment by TroubleMakerBen** [comment]
Honestly, I have no idea who else is out there for this who supports UWP.
