### ISSUE TITLE
Cannot remove plugin

### ISSUE THREAD

**Issue by uloco** [bitstadium/HockeySDK-Cordova#53]
I cannot remove the plugin via command line.

```
$ cordova platform add android
$ cordova platform add ios
$ cordova plugin add cordova-plugin-hockeyapp
Fetching plugin "cordova-plugin-hockeyapp" via npm
Installing "cordova-plugin-hockeyapp" for android
Installing "cordova-plugin-hockeyapp" for ios

$ cordova plugin rm cordova-plugin-hockeyapp
Uninstalling cordova-plugin-hockeyapp from android
Uninstalling cordova-plugin-hockeyapp from ios
Error during processing of action! Attempting to revert...
Error: Uh oh!
Path must be a string. Received undefined
```

**Comment by uloco** [comment]
Guys, this is a really critical bug. I want to remove your plugin from production builds and we are in the middle of a release phase. Removing manually isn't possible without a pretty much amount of work...
Can you please say something about it?

**Comment by TroubleMakerBen** [comment]
Hey,

I'm closing this issue as it's been around for more than a year. Please open it again if you still run into this.

Thx!
Benjamin
