### ISSUE TITLE
Same app id for both Android and iOS App

### ISSUE THREAD

**Issue by ashvin777** [bitstadium/HockeySDK-Cordova#55]
Hi Team,

Is it possible to use the same app id for both andorid and ios applications  for crash reporting ?

In hockeyapp usually for 2 different apps 2 different app ids are generated.

Regards,
Ashvin

**Comment by johnborges** [comment]
Since this is to be used with Cordova why not just do:

```
if(device.platform === 'iOS'){
    hockeyapp.start(succ, err, "APP_ID_IOS");
}
else if(device.platform === 'Android'){
    hockeyapp.start(succ, err, "APP_ID_ANDROID");
}
```

**Comment by ashvin777** [comment]
Thanks.
