### ISSUE TITLE
Android build error with Visual Studio Team Services build

### ISSUE THREAD

**Issue by izaxon** [bitstadium/HockeySDK-Cordova#56]
We have setup continuous integration (CI) for our Ionic app in Visual Studio Team Services (Visual Studio Online).
We added the plugin to the project, but hockeyapp was could not be referenced when built using CI. 
It works when building locally on the dev PC. So we tried to force the plugin to be used in CI by adding a reference to it in the config.xml file. Then build fails with error:

```
2016-09-04T08:58:44.7887913Z     [javac] C:\a\1\s\src\app\platforms\android\src\com\zengularity\cordova\hockeyapp\HockeyApp.java:11: error: package net.hockeyapp.android does not exist
2016-09-04T08:58:44.7887913Z     [javac] import net.hockeyapp.android.CrashManager;
2016-09-04T08:58:44.7887913Z     [javac]                             ^
2016-09-04T08:58:44.7887913Z     [javac] C:\a\1\s\src\app\platforms\android\src\com\zengularity\cordova\hockeyapp\HockeyApp.java:12: error: package net.hockeyapp.android does not exist
2016-09-04T08:58:44.7887913Z     [javac] import net.hockeyapp.android.CrashManagerListener;
2016-09-04T08:58:44.7887913Z     [javac]                             ^
```

**ionic info** shows:

```
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS:
Node Version: v4.4.3
```

Does anyone know how to fix CI builds to make the plugin work?

**Comment by CookieCookson** [comment]
I have this plugin added to my project which builds through VSTS and don't appear to have the issues you are having. What version of `cordova-android` are you running?

Also, are you using a hosted build server with VSTS or is it self-hosted?

**Comment by izaxon** [comment]
I use the hosted build server with VSTS (i.e. not self-hosted).

Cordova version was 6.3.1. Android 5.2.2.

Could the problem be that the hockeyapp plugin in is not retrieved in VSTS?

**Comment by CookieCookson** [comment]
You should have the HockeyApp plugin in your config.xml as a `<plugin>` declaration (you can do this by appending --save when adding the plugin), and during your CI build steps you should do `cordova prepare` so it downloads any new/existing plugins to your project referenced in config.xml. I imagine you are already doing this, but make sure this is the case :)

**Comment by TroubleMakerBen** [comment]
Hey folks, 
Are you still seeing this issue, please let me know so we can look into this.

Best,
Benny

**Comment by TroubleMakerBen** [comment]
Hey,

I'm closing this issue as it's been around since 2016. Please open it again if you still run into this.

Thx!
Benjamin
