### ISSUE TITLE
Issue while doing build with Intel XDK

### ISSUE THREAD

**Issue by amaltv** [bitstadium/HockeySDK-Cordova#59]
I am building a hybrid app and would like to integrate HockeyApp. I am using Intel XDK for doing the build. While doing the build from Intel XDK, its giving an error saying "Gradle script not supported". Is it possible to have the gradle script removed from the src android folder?

**Comment by TroubleMakerBen** [comment]
Hey,

I'm closing this issue as it's been around since 2016. Please open it again if you still run into this.

Thx!
Benjamin
