### ISSUE TITLE
Android - composeFeedback failure - "failed to take screenshot"

### ISSUE THREAD

**Issue by ds8k** [bitstadium/HockeySDK-Cordova#60]
The following results in a `failed to take screenshot` error only on Android:

```
var failure = function(a) { console.log(a); };
var success = function(a) { console.log(a); };
window.hockeyapp.composeFeedback(success, failure, true, {});
```

This is happening on the two test devices I have:
- Samsung Galaxy S6 running Android 5.1.1
- Nexus 6P running 7.0

```
$ cordova -v
6.3.1

$ cordova platforms
Installed platforms:
  android 5.1.1
  ios 4.1.1
```

If I pass in `false` for the screenshot parameter it works, as well as the normal `feedback()` call.

**Comment by bmwertman** [comment]
Did you solve this? 

As far as I can tell the `window.hockeyapp` object does not have a `composeFeedback` method defined within it. 

I have the latest version 2.2.2 and there is only a `feedback` method as shown below.

![screen shot 2016-10-17 at 3 13 46 pm](https://cloud.githubusercontent.com/assets/2573903/19451886/9115d3a0-947c-11e6-8cc7-dd204bb608ab.png)

**Comment by ds8k** [comment]
I believe we're running 2.2.3 (we specified that tag when installing)

**Comment by bmwertman** [comment]
OK thanks. I ended up using `$http` to hit their API endpoint and made my own form views.

**Comment by TroubleMakerBen** [comment]
Hey,

I'm closing this issue as it's been around since 2016. Please open it again if you still run into this.

Thx!
Benjamin
