### ISSUE TITLE
hockeyapp cordova plugin: plugin is already started!

### ISSUE THREAD

**Issue by kevinverelst** [bitstadium/HockeySDK-Cordova#61]
We are receiving a lot of errors when we are starting the hockeyAppSdk.
The error we receive is: hockeyapp cordova plugin: plugin is already started!

We think the webview our app is hosted in, crashed, restarted the app and in the startup of our app, we try to start the hockeyAppSdk again.
Could this be the issue?

**Comment by kevinverelst** [comment]
Seems like the cause could be that our webview is crashing and refreshing our app which causes the SDK to be called again

**Comment by TroubleMakerBen** [comment]
Hey,

I'm closing this issue as it's been around for at least a year. Please open it again if you still run into this.

Thx!
Benjamin
