### ISSUE TITLE
Authentication other than Anonymous

### ISSUE THREAD

**Issue by whodeee** [bitstadium/HockeySDK-Cordova#62]
Why does the app crash when using non-anonymous authentication?
It would be great to add other authentication methods.

**Comment by TroubleMakerBen** [comment]
Hey @whodeee,
We currently have no plans to port the authentication methods to Cordova.

We are hard at work on the all new [Mobile Center SDKs](https://www.hockeyapp.net/mobile-center/about/) and while there is no Cordova SDK yet, there will be eventually.

I hope you understand that we only have limited resources. Please bear with us and thanks for using HockeyApp.

Benny
