### ISSUE TITLE
Check new version

### ISSUE THREAD

**Issue by aspcsharp9** [bitstadium/HockeySDK-Cordova#63]
When is new version available on call hockeyapp.checkForUpdate(); appears alert, any solution when new version is not available any feedback alert after call hockeyapp.checkForUpdate().

**Comment by okulygin** [comment]
you can try 
```js
hockeyapp.checkForUpdate(function (successContext) {
  if (successContext === 'OK') {
    //// handle successfull checkForUpdate call
  }
})
```

**Comment by philib** [comment]
Hi,
the context doesnt differ between "update available" and "no update available". Context for both scenarios is "OK". Is there an other solution?

**Comment by TroubleMakerBen** [comment]
Hey,

I'm not sure if I understand the issue correctly. Are you saying that you want a method that returns if an update is available? Or are you looking for an alert that shows up and tells the users that there is no update available?

Best,
Benny

**Comment by okulygin** [comment]
It would be great to have an API which returns some result like whether update is available or not, and if yes, then some metadata of the update like date, version, release notes...

**Comment by aspcsharp9** [comment]
Example:
On my phone I have version 1.0.0. On hockeyapp 1.0.1. I can updet my app, that is OK.
On my phone I have version 1.0.0. On hockeyapp 1.0.0. Any alert eg. On your phone is last version!

**Comment by saschwarz** [comment]
@TroubleMakerBen I think if `checkforUpdate` gave you version information in the callback we could compare it to the currently installed version.

**Comment by okulygin** [comment]
yeah, it should work, ideally if checkForUpdate provides an object with the latest version metadata

**Comment by TroubleMakerBen** [comment]
Hey @okulygin,

thx for the confirmation. There is an API in HA-Android that returns a boolean with that information and I've added a story to our backlog to expose such an API in the native iOS SDK and then update the wrapper SDKs. That said, we're hard at work on [Mobile Center](https://www.hockeyapp.net/mobile-center/about/) so I can't say when that's coming. It might be quite some time. That said, I'm happy to accept PRs for any of our SDKs that are related to this.

Best,
Benjamint
