### ISSUE TITLE
Crash report dialog still apears when autosend is set to true

### ISSUE THREAD

**Issue by digitalbath** [bitstadium/HockeySDK-Cordova#64]
I've set `autosend` to `true` but I'm still getting the crash report dialog when opening the app after a crash.

I'm doing it like this:
`hockeyapp.start(null, null, config.hockyId, true);`

Is this a bug or am I doing something wrong?

**Comment by TroubleMakerBen** [comment]
Hey,

I'm closing this issue as it's been around for at least a year. Please open it again if you still run into this.

Thx!
Benjamin
