### ISSUE TITLE
Update HockeyApp SDK for NSPhotoLibraryUsageDescription issue

### ISSUE THREAD

**Issue by SvenTobback** [bitstadium/HockeySDK-Cordova#66]
Hi,

In the master branch the NSPhotoLibraryUsageDescription is added to the plist to resolve the iOS 10 privacy issue, even if the feedback feature isn't used.

In following post it is stated that HockeyApp SDK version 4.1.1 removes the feedback feature by default:

[https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/known-issues-with-ios#app-store-rejection-because-of-missing-code-nsphotolibraryusagedescription-code-](url)

Users that don't use the feedback feature (like me) shouldn't be forced to include the photo permission.

Kind Regards,

**Comment by phpfs** [comment]
Hi,

any updates to this?

Greetings, phpfs

**Comment by TroubleMakerBen** [comment]
Hi guys,

We're about to release 2.2.3 which will wrap the latest SDKs. It will wrap the SDK with all features. To have a cordova version that uses the "default" SDK, you will need to use your own fork.

Best,
Benjamin
