### ISSUE TITLE
hockeyapp.composeFeedback function missing on Android & IOS

### ISSUE THREAD

**Issue by fephil** [bitstadium/HockeySDK-Cordova#67]
Hi,

When using Version 2.2.2 of the plugin (latest release) on Android, the hockeyapp.composeFeedback function is missing. Please see attached screenshot taken from the console:

Thanks.

EDIT: This is also happening on IOS 10.

![image](https://cloud.githubusercontent.com/assets/1689044/22973920/bf156cf2-f377-11e6-9b82-df9d7738ea06.png)

**Comment by fephil** [comment]
I have been able to fix this by directly pulling the plugin from GitHub rather than using v2.2.2. Perhaps a new version can be released?

**Comment by TroubleMakerBen** [comment]
Hey @fephil,

Have you tried 2.2.3 or 2.2.4? =)

**Comment by TroubleMakerBen** [comment]
Closing this as we haven't heard from anyone since then.
