### ISSUE TITLE
Android 7 (7.1) does not detect (prompt) new versions 

### ISSUE THREAD

**Issue by vziukas** [bitstadium/HockeySDK-Cordova#69]
We found that this plugin does not work correctly on Android 7 (7.1). Does not prompt to update app.

Any advises ? Android 6, 5, 4.4 and iOS its all ok.

**Comment by TroubleMakerBen** [comment]
Hey @vziukas, can you check if this still happens with the latest release, please?

**Comment by vziukas** [comment]
Its all ok with latest release. Thanks.
