### ISSUE TITLE
checkForUpdate() does not show dialogs in Android 6+

### ISSUE THREAD

**Issue by okulygin** [bitstadium/HockeySDK-Cordova#70]
There is no update prompt on Android 6+. Same app on Android 4, 5 works well. To repro this issue app should not be installed from adb.

**Comment by okulygin** [comment]
Looks like this is related to https://github.com/bitstadium/HockeySDK-Android/issues/161

**Comment by TroubleMakerBen** [comment]
I just merged your PR and there will be an updated release soon.
