### ISSUE TITLE
Feature request - update SDK to latest version

### ISSUE THREAD

**Issue by galvanu** [bitstadium/HockeySDK-Cordova#75]
Hi, I'm interested in tackEvent api which support properties and measurements.
Since the current SDK version doesn't contain this API (it exists from 4.1.1) I can't use it in my cordova app.

If you need any help with this, I can help and create a new pull request with these changes, I just need to know if there are any new APIs that should be added in addition to the new trackEvent method.

Thanks

**Comment by TroubleMakerBen** [comment]
Hey @galvanu,

thanks for getting in touch. Please go ahead and create a PR, I'm happy to merge it.

Benny

**Comment by TroubleMakerBen** [comment]
Closing this issue. The plugin will be updated with the latest native SDKs next week.
