### ISSUE TITLE
Intermittent App Crashing on iPhone 7, and iPhone SE on iOS 10.3.2

### ISSUE THREAD

**Issue by Jacob-McKay** [bitstadium/HockeySDK-Cordova#81]
I suspect the issue lies with the HockeyApp SDK because when I remove this plugin my issue goes away, and when running the app in xcode with the plugin I see:

> THREAD WARNING: ['Hockeyapp'] took '13.104980' ms. Plugin should use a background thread.

in the debug console.

I have been using the HockeyApp SDK on iOS and Android without issue until I tested with combination of hardware and OS.  Hope I'm not totally wrong and wasting your time!

**Comment by bmourat** [comment]
Hi @Jacob-McKay 

Could you please provide information on what part of SDK you are using when crash happens?
And does this crash happens only on real devices (iPhone 7, iPhone SE) with 10.3.2, or it crashes also on emulator?

Thanks,
Murat

**Comment by Jacob-McKay** [comment]
Thanks for responding, I missed the email.  I will try to reproduce it today to answer your questions definitively.

**Comment by Jacob-McKay** [comment]
The folks testing my app are still having the same problem without the cordova hockeyapp plugin.  We should be able to rule out that HockeyApp is the culprit, I still get the warning in xcode, but I'm not going to attribute my failing app startups to SDK or my use of the SDK.

**Comment by Jacob-McKay** [comment]
To help the next person along who is suspect of the hockeyapp message in xcode, and whose app has the same symptoms as mine, the issue was a race condition for many services checking platform.ready.  I ended up putting all app initialization in one platform.ready handler and I no longer see intermittent startup issues.

Thanks for you responsiveness to my issue @bmourat

**Comment by bmourat** [comment]
No problem) Glad you've figured your issue out, and thanks for sharing your solution!
