### ISSUE TITLE
iOS checkForUpdate implicit on app start and on app foreground cannot be disabled

### ISSUE THREAD

**Issue by polecito** [bitstadium/HockeySDK-Cordova#82]
Hi,
I'm using latest version of plugin with iOS SDK to 4.1.5.
I see alerts for new versions, but I want them to be shown only when I manually call checkForUpdate().

I've checked [BITHockeyManager sharedInstance].updateManager.checkForUpdateOnLaunch on AppDelegate and is NO. Why are the alerts appearing even if I don't call checkForUpdate() manually?

I've checked also the updateManager.updateSetting and it's BITUpdateCheckStartup, I tried to set to BITUpdateCheckManually but is not working. Where and how can I update this value?

Thanks!

**Comment by tabrindle** [comment]
Having the same issue. I would like to be able to optionally disable this for UI tests, and enable it for actual beta testers.

**Comment by TroubleMakerBen** [comment]
Hey folks,

we're looking into this.

Best,
Benny

**Comment by bmourat** [comment]
Hi @polecito @tabrindle 

It seems like it was not possible to disable automatic check for updates on ios using current version of plugin, so i created PR #83 for this and if everything is ok hopefully it will be merged.

Best,
Murat

**Comment by tabrindle** [comment]
Thanks @bmourat I think we can close this issue now.
