### ISSUE TITLE
Not work in latest ?

### ISSUE THREAD

**Issue by shalinasanga** [bitstadium/HockeySDK-Cordova#87]
hi,
My Cordova project has following details:
Installed platforms:
  android 6.3.0

<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="26" />

In Login view.js, onDeviceReady function i add : `hockeyapp.start(null, null, '0b7c4d1939a64570a2bd4b38732d1e0e', true);`

And in another js i call `hockeyapp.forceCrash();` neither app crashes nor error reports available in hockey app

Did i do anything wrong ? any solution

**Comment by bmourat** [comment]
Hi @shalinasanga!

You are doing everything correctly, and the app should indeed crash. Can you share your setup code and information on what version of the plugin you are using? Also, are you testing on emulator or device, and on what Android version?

Best,
Murat

**Comment by shalinasanga** [comment]
hi,
this is the hockey version :  `<plugin name="cordova-plugin-hockeyapp" spec="^5.0.1" />`
And i used `cordova plugin add cordova-plugin-hockeyapp@latest` to add plugin.

**Comment by bmourat** [comment]
@shalinasanga 
Could you please try [this project](https://github.com/bmourat/HockeySDK-CordovaDemo)  and confirm that crash button does not crash the app. Just clone it and install hockeysdk plugin with `cordova plugin add cordova-plugin-hockeyapp@latest`

Best,
Murat

**Comment by shalinasanga** [comment]
Sorry for the inconvenience caused !!! it worked, but  `hockeyapp.forceCrash();` is not work in my button click function (javascript button click functionality working fine), no crash report came to account.
so i put crash code in some other place and it worked.

**Comment by TroubleMakerBen** [comment]
Hi @shalinasanga 
Good to hear that things worked out for you. 

I'm closing this issue. Please get in touch here or through support any time!

Benjamin

**Comment by shalinasanga** [comment]
Thank you very much guys. This plugin is really nice and having responsive team like you is fortune.
Thanks again. cheers !!!
