### ISSUE TITLE
Nothing showing up on dashboard

### ISSUE THREAD

**Issue by dland512** [bitstadium/HockeySDK-Cordova#90]
For some reason I'm having trouble seeing the crashes and events in the hockey app dashboard. The sdk calls are completing successfully. I even tried downloading [this project](https://github.com/bmourat/HockeySDK-CordovaDemo) and replacing the app id with the one for my app and I'm still having issues.

```
onDeviceReady: function() {
    this.receivedEvent('deviceready');
    hockeyapp.start(null, null, 'abc123abc123abc123abc123abc123', true);
    ...
}
```

Using the demo app, on Android crashes to show up on the dashboard, but event tracking does not. On iOS neither crashes not event tracking show up. I must be doing something wrong her but I can't figure out what.

Here is my system info:

```
$ cordova plugin ls
cordova-plugin-hockeyapp 5.0.1 "HockeyApp"
cordova-plugin-whitelist 1.3.2 "Whitelist"
```
```
$ cordova platform ls
Installed platforms:
  android 6.3.0
  ios 4.5.4
```

**Comment by dland512** [comment]
Never mind. It appears to be working. I guess sometimes it just takes several minutes for things to show up on the dashboard.

**Comment by TroubleMakerBen** [comment]
Hey David,

I'm glad the issue solved itself. Usually crash reports are visible within a minute, often within 10-15s after they were sent. Events can take a few minutes.

Best,
Benjamin
