### ISSUE TITLE
Could not find :HockeySDK-5.0.4 in Cordova-Android@7.0.0

### ISSUE THREAD

**Issue by NeoLSN** [bitstadium/HockeySDK-Cordova#97]
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find :HockeySDK-5.0.4:.

**Comment by TroubleMakerBen** [comment]
Hey @NeoLSN,

We're working on fixing compatibility with Cordova 7.0.0, stay tuned and apologies for the inconvenience!

Benjamin

**Comment by georgeMuraveiAlkh** [comment]
The same problem here - my cordova-plugin-media doesn't work with cordova-android lower than 7.0.0 but hockeyapp doesn't work with 7.0.0

**Comment by TroubleMakerBen** [comment]
We just released version 5.1.2 of the Cordova plugin which makes it compatible with Cordova 7.

Thx for your patience everyone & for using HockeyApp!

Benjamin

**Comment by sckumar** [comment]
Same issue appearing in Cordova 8.0.0
